<?php
echo 'IELECTRO NESH' . PHP_EOL;
echo '============================' . PHP_EOL;
echo 'Version: ' . NESH_VERSION . PHP_EOL;
echo 'PHP: ' . PHP_VERSION . PHP_EOL;
echo 'Operating System: ' . PHP_OS . PHP_EOL;
echo PHP_EOL;
echo 'USAGE' . PHP_EOL;
echo '  php nesh <command> [arguments]' . PHP_EOL;
echo PHP_EOL;
echo 'COMMANDS' . PHP_EOL;
echo '  install                              Initialize databases and regenerate nesh.js.' . PHP_EOL;
echo '  deploy <URL> [database]              Create a sibling deployment folder named from' . PHP_EOL;
echo '                                       the domain, configure URLs, optionally unify' . PHP_EOL;
echo '                                       all databases, build SQL, clear user assets,' . PHP_EOL;
echo '                                       and create a ZIP archive.' . PHP_EOL;
echo '  database <app> <database> <URL>        Rename one application database inside an' . PHP_EOL;
echo '                                       existing deployment folder.' . PHP_EOL;
echo '  help                                 Display this help page.' . PHP_EOL;
echo PHP_EOL;
echo 'EXAMPLES' . PHP_EOL;
echo '  php nesh install' . PHP_EOL;
echo '  php nesh deploy https://www.example.it my_ielectro' . PHP_EOL;
echo '  php nesh deploy https://ielectro.altervista.org ielectro' . PHP_EOL;
echo '  php nesh deploy https://www.example.it' . PHP_EOL;
echo '  php nesh database account new_account https://ielectro.example.it' . PHP_EOL;
