<?php
echo 'IELECTRO NESH' . PHP_EOL;
echo '============================' . PHP_EOL;
echo 'Version: ' . NESH_VERSION . PHP_EOL;
echo 'PHP: ' . PHP_VERSION . PHP_EOL;
echo 'Operating System: ' . PHP_OS . PHP_EOL;
echo PHP_EOL;
echo 'USAGE' . PHP_EOL;
echo '  php nesh <command> [arguments]' . PHP_EOL;
echo PHP_EOL;
echo 'COMMANDS' . PHP_EOL;
echo '  install                                   Initialize databases and regenerate nesh.js.' . PHP_EOL;
echo '  deploy <URL> [version] [options]          Create or overwrite a deployment folder,' . PHP_EOL;
echo '                                            configure URLs, stamp assets, and create ZIP.' . PHP_EOL;
echo '                                            Options: --db, --db-host, --db-user, --db-pass,' . PHP_EOL;
echo '                                            --app <folder>' . PHP_EOL;
echo '  database <app> <database> <URL>           Rename one application database inside an' . PHP_EOL;
echo '                                            existing deployment folder.' . PHP_EOL;
echo '  fix-images [options]                      Rename Dyscover image asset files to match their' . PHP_EOL;
echo '                                            corresponding post UUIDs in the database.' . PHP_EOL;
echo '                                            Options: --user <id>, --dry-run, --app <folder>' . PHP_EOL;
echo '  help                                      Display this help page.' . PHP_EOL;
echo PHP_EOL;
echo 'EXAMPLES' . PHP_EOL;
echo '  php nesh install' . PHP_EOL;
echo '  php nesh deploy https://www.example.it 1.2.1 --db my_ielectro' . PHP_EOL;
echo '  php nesh deploy https://ielectro.altervista.org 1.2.1 --db my_ielectro \\' . PHP_EOL;
echo '    --db-host localhost --db-user myuser --db-pass mypass' . PHP_EOL;
echo '  php nesh deploy https://www.example.it 1.2.1 --app account' . PHP_EOL;
echo '  php nesh deploy https://www.example.it 1.2.1' . PHP_EOL;
echo '  php nesh database account new_account https://ielectro.example.it' . PHP_EOL;
