<?php
echo 'IELECTRO NESH' . PHP_EOL;
echo '============================' . PHP_EOL;
echo 'Version: ' . NESH_VERSION . PHP_EOL;
echo 'PHP: ' . PHP_VERSION . PHP_EOL;
echo 'Operating System: ' . PHP_OS . PHP_EOL;
echo PHP_EOL;
echo 'USAGE' . PHP_EOL;
echo '  php nesh <command> [arguments]' . PHP_EOL;
echo PHP_EOL;
echo 'COMMANDS' . PHP_EOL;
echo '  install                   Initialize databases and regenerate nesh.js.' . PHP_EOL;
echo '  domain <URL>              Configure deployment URLs for all applications.' . PHP_EOL;
echo '  db --all [output.sql]     Build one SQL file from all application /database folders.' . PHP_EOL;
echo '                            Order: account -> admin -> dyscover -> dominions.' . PHP_EOL;
echo '                            Default output: nesh/database/ielectro.sql' . PHP_EOL;
echo '  db <application> <db>     Rename the database for one application.' . PHP_EOL;
echo '  help                      Display this help page.' . PHP_EOL;
echo PHP_EOL;
echo 'EXAMPLES' . PHP_EOL;
echo '  php nesh install' . PHP_EOL;
echo '  php nesh domain https://ielectro.com' . PHP_EOL;
echo '  php nesh domain http://localhost/ielectro' . PHP_EOL;
echo '  php nesh db --all' . PHP_EOL;
echo '  php nesh db --all backup/ielectro.sql' . PHP_EOL;
echo '  php nesh db account ielectro_new_account' . PHP_EOL;
